ifram标题:
  type: xpath
  value: "//div[@class='panel-title']"
增加:
  type: xpath
  value: "//*[@class='l-btn-icon icon-add']"
修改:
  type: xpath
  value: "//*[@class='l-btn-icon icon-edit']"
删除:
  type: xpath
  value: "//*[@class='l-btn-icon icon-remove']"
保存:
  type: xpath
  value: "//div[@class='datagrid-body']/table/tbody/tr[last()]/td[last()]/div/a[1]"
撤销:
  type: xpath
  value: "//div[@class='datagrid-body']/table/tbody/tr[last()]/td[last()]/div/a[2]"
删除行:
  type: xpath
  value: "//div[@class='datagrid-body']/table/tbody/tr[last()]/td[last()]/div/a[3]"
确定:
  type: xpath
  value: "//span[contains(text(), '确定')]"
取消:
  type: xpath
  value: "//span[contains(text(), '取消')]"
最后一行:
  type: xpath
  value: "//table[@class='datagrid-btable']/tbody/tr[last()]"
退出:
  type: xpath
  value: "//li[@class='quit']"
名称输入框:
  type: xpath
  value: "//td[@field='name']/div/table/tbody/tr/td/input"
编码输入框:
  type: xpath
  value: "//td[@field='code']/div/table/tbody/tr/td/span/input[1]"
厂商名称复选框:
  type: xpath
  value: "//td[@field='firmName']/div/table/tbody/tr/td/span"
厂商选择:
  type: xpath
  value: "//div[@class='panel combo-p panel-htop']/div/div[contains(text(), '多米科技')]"
产品能力复选框:
  type: xpath
  value: "//td[@field='abilityDesc']/div/table/tbody/tr/td/span"
全选:
  type: xpath
  value: "//td[@field='ck']/div/input"




